version: '3'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:latest
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      URL: jdbc:postgresql://db:5432/postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
